Lesson 5. Array listing
snoozee/JavaCourse pull request #4
Opened 2023-06-16 09:51 UTC by snoozee

2023-06-16 10:04 UTC, SergeyPasko requested changes
Hi. Currently it's only a half of homework

2023-06-16 10:04 UTC, SergeyPasko commented on src/main/java/collections/OccurrenceCounter.java
> +        List<String> wordList = List.of("Bradley", "Leopard-1", "Leopard-2", "T-72", "Bradley", "T-90");
Good names

2023-06-16 12:54 UTC, SergeyPasko reviewed
Cool

2023-06-16 12:54 UTC, SergeyPasko commented on src/main/java/phonebook/TelephoneDirectory.java
> +    private List<Record> phoneBook;
`= new  ArrayList<>();`

In this case you cannot write a constructor

2023-06-16 12:54 UTC, SergeyPasko commented on src/main/java/phonebook/Record.java
> +public class Record {
`record` is a keyword in java. If possible, better to use synonims

2023-07-11 07:33 UTC, SergeyPasko approved these changes
Cool

2023-07-11 10:17 UTC, snoozee commented on src/main/java/collections/OccurrenceCounter.java
> +        List<String> wordList = List.of("Bradley", "Leopard-1", "Leopard-2", "T-72", "Bradley", "T-90");
Thx

2023-07-11 10:18 UTC, merged